{
 "title": "System Metric",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "timezone",
    "label": "timezone",
    "query": {
     "query": "label_values(machine_timezone_info,timezoneName)"
    }
   },
   {
    "name": "machine_hw_info",
    "label": "machine_hw_info",
    "query": {
     "query": "label_values(machine_hw_info,version)"
    }
   },
   {
    "name": "device",
    "query": "mac-mini1,mac-book1,mac-mini2,mac-studio1,mac-studio2,mac-studio3,mac-studio4"
   },
   { "name": "query0" }
  ]
 },
 "panels": [
  {
   "title": "Machine Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "machine_uptime{device=\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(machine_memory_used{device=\"$device\"} / machine_memory_total{device=\"$device\"}) * 100",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "machine_cpu_load_currentLoad{device=\"$device\"}",
     "legendFormat": "CPU Load"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 } },
  {
   "title": "CPU Speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ghz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "machine_cpu_speed{device=\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "machine_memory_free{device=\"$device\"} / (1024 * 1024 * 1024)",
     "legendFormat": "Memory Free"
    },
    {
     "expr": "machine_memory_used{device=\"$device\"} / (1024 * 1024 * 1024)",
     "legendFormat": "Memory Used"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "machine_fs_size_available{mount=\"/\",device=\"$device\"} / (1024 * 1024 * 1024)",
     "legendFormat": "Disk Available"
    },
    {
     "expr": "machine_fs_size_used{mount=\"/\",device=\"$device\"} / (1024 * 1024 * 1024)",
     "legendFormat": "Disk Used"
    }
   ]
  },
  {
   "title": "Total processes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "machine_processes_all{device=\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "System Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Machine Hardware Info",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "machine_os_info{device=\"$device\"}",
     "legendFormat": "__auto"
    },
    { "legendFormat": "__auto" }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "CPU Load",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "machine_cpu_load_currentLoad{device=\"$device\"}",
     "legendFormat": "CPU Load"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "machine_cpu_load_currentLoad{device=\"$device\"}",
     "legendFormat": "CPU Load"
    }
   ]
  },
  {
   "title": "Top Processes by CPU",
   "type": "table",
   "gridPos": { "h": 22, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "machine_processes_list_cpu{device=\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Load Breakdown",
   "type": "piechart",
   "description": "CPU load breakdown by type",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "machine_cpu_load_currentLoadUser{device=\"$device\"}",
     "legendFormat": "User Load"
    },
    {
     "expr": "machine_cpu_load_currentLoadSystem{device=\"$device\"}",
     "legendFormat": "System Load"
    },
    {
     "expr": "machine_cpu_load_currentLoadIdle{device=\"$device\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "machine_cpu_load_currentLoadIrq{device=\"$device\"}",
     "legendFormat": "IRQ Load"
    }
   ]
  },
  {
   "title": "CPU Load Breakdown",
   "type": "timeseries",
   "description": "CPU load breakdown by type",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "machine_cpu_load_currentLoadUser{device=\"$device\"}",
     "legendFormat": "User Load"
    },
    {
     "expr": "machine_cpu_load_currentLoadSystem{device=\"$device\"}",
     "legendFormat": "System Load"
    },
    {
     "expr": "machine_cpu_load_currentLoadIdle{device=\"$device\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "machine_cpu_load_currentLoadIrq{device=\"$device\"}",
     "legendFormat": "IRQ Load"
    }
   ]
  },
  {
   "title": "CPU Speed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ghz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "machine_cpu_speed{device=\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Speed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ghz" } },
   "targets": [
    {
     "expr": "machine_cpu_speed{device=\"$device\"}",
     "legendFormat": "CPU Speed"
    },
    {
     "expr": "machine_cpu_speedMin{device=\"$device\"}",
     "legendFormat": "Min Speed"
    },
    {
     "expr": "machine_cpu_speedMax{device=\"$device\"}",
     "legendFormat": "Max Speed"
    },
    {
     "expr": "machine_cpu_current_speed_avg{device=\"$device\"}",
     "legendFormat": "Current Avg"
    },
    {
     "expr": "machine_cpu_current_speed_max{device=\"$device\"}",
     "legendFormat": "Current Max"
    },
    {
     "expr": "machine_cpu_current_speed_min{device=\"$device\"}",
     "legendFormat": "Current Min"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "machine_memory_total{device=\"$device\"} / (1024 * 1024 * 1024)",
     "legendFormat": "Memory Total"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "machine_memory_available{device=\"$device\"} / (1024 * 1024 * 1024)",
     "legendFormat": "Memory Available"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "machine_memory_swapused{device=\"$device\"} / (1024 * 1024 * 1024)",
     "legendFormat": "Swap Used"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "machine_memory_swaptotal{device=\"$device\"} / (1024 * 1024 * 1024)",
     "legendFormat": "Swap Total"
    }
   ]
  },
  {
   "title": "Top Processes by Memory",
   "type": "table",
   "gridPos": { "h": 20, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "machine_processes_list_mem{device=\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(machine_memory_used{device=\"$device\"} / machine_memory_total{device=\"$device\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 4, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(machine_memory_used{device=\"$device\"} / machine_memory_total{device=\"$device\"}) * 100",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "machine_memory_free{device=\"$device\"} / (1024 * 1024 * 1024)",
     "legendFormat": "Memory Free"
    },
    {
     "expr": "machine_memory_used{device=\"$device\"} / (1024 * 1024 * 1024)",
     "legendFormat": "Memory Used"
    }
   ]
  },
  {
   "title": "Memory Active/BuffCache/Reclaimable",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "machine_memory_active{device=\"$device\"} / (1024 * 1024 * 1024)",
     "legendFormat": "Memory Active"
    },
    {
     "expr": "machine_memory_buffcache{device=\"$device\"} / (1024 * 1024 * 1024)",
     "legendFormat": "Memory Buff/Cache"
    },
    {
     "expr": "machine_memory_reclaimable{device=\"$device\"} / (1024 * 1024 * 1024)",
     "legendFormat": "Memory Reclaimable"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "machine_fs_size_available{mount=\"/\",device=\"$device\"} / (1024 * 1024 * 1024)",
     "legendFormat": "Disk Available"
    },
    {
     "expr": "machine_fs_size_used{mount=\"/\",device=\"$device\"} / (1024 * 1024 * 1024)",
     "legendFormat": "Disk Used"
    }
   ]
  },
  {
   "title": "Filesystem Usage",
   "type": "timeseries",
   "description": "Filesystem usage by mount point",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "machine_fs_size_use{mount!=\"\",device=\"$device\"}",
     "legendFormat": "{{mount}}"
    }
   ]
  },
  {
   "title": "Filesystem I/O",
   "type": "timeseries",
   "description": "Filesystem I/O statistics",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "machine_fs_stats_rx_sec{device=\"$device\"}",
     "legendFormat": "Read"
    },
    {
     "expr": "machine_fs_stats_wx_sec{device=\"$device\"}",
     "legendFormat": "Write"
    },
    {
     "expr": "machine_fs_stats_tx_sec{device=\"$device\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Disk IO Rates",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "machine_disksio_rIO_sec{device=\"$device\"}",
     "legendFormat": "Read IO/sec"
    },
    {
     "expr": "machine_disksio_wIO_sec{device=\"$device\"}",
     "legendFormat": "Write IO/sec"
    },
    {
     "expr": "machine_disksio_tIO_sec{device=\"$device\"}",
     "legendFormat": "Total IO/sec"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "Network Traffic",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(machine_network_stats_rx_sec{device=\"$device\"} * 8)",
     "legendFormat": "Rx"
    },
    {
     "expr": "sum(machine_network_stats_tx_sec{device=\"$device\"} * 8)",
     "legendFormat": "Tx"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "description": "Network traffic per interface",
   "gridPos": { "h": 8, "w": 9, "x": 4, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "machine_network_stats_rx_sec{device=\"$device\"} * 8",
     "legendFormat": "Rx {{iface}}"
    },
    {
     "expr": "machine_network_stats_tx_sec{device=\"$device\"} * 8",
     "legendFormat": "Tx {{iface}}"
    }
   ]
  },
  {
   "title": "Network Errors & Dropped Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "machine_network_stats_rx_errors{device=\"$device\"}",
     "legendFormat": "Rx Errors {{iface}}"
    },
    {
     "expr": "machine_network_stats_tx_errors{device=\"$device\"}",
     "legendFormat": "Tx Errors {{iface}}"
    },
    {
     "expr": "machine_network_stats_rx_dropped{device=\"$device\"}",
     "legendFormat": "Rx Dropped {{iface}}"
    },
    {
     "expr": "machine_network_stats_tx_dropped{device=\"$device\"}",
     "legendFormat": "Tx Dropped {{iface}}"
    }
   ]
  },
  {
   "title": "Network Connections",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "machine_network_connections_state{device=\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Processes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 } },
  {
   "title": "Total number of processes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 99 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "machine_processes_all{device=\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running Processes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 99 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "machine_processes_running{device=\"$device\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Statistics",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 15, "x": 9, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "machine_processes_all{device=\"$device\"}",
     "legendFormat": "All Processes"
    },
    {
     "expr": "machine_processes_running{device=\"$device\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "machine_processes_blocked{device=\"$device\"}",
     "legendFormat": "Blocked"
    },
    {
     "expr": "machine_processes_sleeping{device=\"$device\"}",
     "legendFormat": "Sleeping"
    }
   ]
  },
  {
   "title": "Process Statistics",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "machine_processes_running{device=\"$device\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "machine_processes_blocked{device=\"$device\"}",
     "legendFormat": "Blocked"
    },
    {
     "expr": "machine_processes_sleeping{device=\"$device\"}",
     "legendFormat": "Sleeping"
    }
   ]
  }
 ]
}