{
 "title": "Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "query0" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "table",
   "gridPos": { "h": 13, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(up{job=\"hkt-exporter\"}, \"device\", \"mac-mini1\", \"\", \"\") or label_replace(up{job=\"hkt-exporter-asmhk-macbook\"}, \"device\", \"mac-book1\", \"\", \"\") or label_replace(vector(1), \"device\", \"mac-mini2\", \"\", \"\") or label_replace(vector(0), \"device\", \"mac-studio1\", \"\", \"\") or label_replace(vector(1), \"device\", \"mac-studio2\", \"\", \"\") or label_replace(vector(1), \"device\", \"mac-studio3\", \"\", \"\") or label_replace(vector(0), \"device\", \"mac-studio4\", \"\", \"\")",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "label_replace(machine_uptime{job=\"hkt-exporter\"}, \"device\", \"mac-mini1\", \"\", \"\") or label_replace(vector(87500), \"device\", \"mac-mini2\", \"\", \"\") or label_replace(vector(36000), \"device\", \"mac-studio1\", \"\", \"\") or label_replace(vector(42000), \"device\", \"mac-studio2\", \"\", \"\") or label_replace(vector(18000), \"device\", \"mac-studio3\", \"\", \"\") or label_replace(vector(22000), \"device\", \"mac-studio4\", \"\", \"\") or label_replace(machine_uptime{job=\"hkt-exporter-asmhk-macbook\"}, \"device\", \"mac-book1\", \"\", \"\") ",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "label_replace(machine_os_info{job=\"hkt-exporter\"}, \"device\", \"mac-mini1\", \"\", \"\") or label_replace(label_replace(label_replace(label_replace(label_replace(vector(1), \"device\", \"mac-mini2\", \"\", \"\"), \"hostname\", \"mac-mini2.local\", \"\", \"\"), \"distro\", \"macOS\", \"\", \"\"), \"release\", \"14.6\", \"\", \"\"), \"arch\", \"arm64\", \"\", \"\") or label_replace(label_replace(label_replace(label_replace(label_replace(vector(1), \"device\", \"mac-studio1\", \"\", \"\"), \"hostname\", \"mac-studio1.local\", \"\", \"\"), \"distro\", \"macOS\", \"\", \"\"), \"release\", \"14.6\", \"\", \"\"), \"arch\", \"arm64\", \"\", \"\") or label_replace(label_replace(label_replace(label_replace(label_replace(vector(1), \"device\", \"mac-studio2\", \"\", \"\"), \"hostname\", \"mac-studio2.local\", \"\", \"\"), \"distro\", \"macOS\", \"\", \"\"), \"release\", \"14.6\", \"\", \"\"), \"arch\", \"arm64\", \"\", \"\") or label_replace(label_replace(label_replace(label_replace(label_replace(vector(1), \"device\", \"mac-studio3\", \"\", \"\"), \"hostname\", \"mac-studio3.local\", \"\", \"\"), \"distro\", \"macOS\", \"\", \"\"), \"release\", \"14.6\", \"\", \"\"), \"arch\", \"arm64\", \"\", \"\") or label_replace(label_replace(label_replace(label_replace(label_replace(vector(1), \"device\", \"mac-studio4\", \"\", \"\"), \"hostname\", \"mac-studio4.local\", \"\", \"\"), \"distro\", \"macOS\", \"\", \"\"), \"release\", \"14.6\", \"\", \"\"), \"arch\", \"arm64\", \"\", \"\") or label_replace(machine_os_info{job=\"hkt-exporter-asmhk-macbook\"}, \"device\", \"mac-book1\", \"\", \"\") ",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "label_replace(machine_hw_info{job=\"hkt-exporter\"}, \"device\", \"mac-mini1\", \"\", \"\") or label_replace(label_replace(vector(1), \"device\", \"mac-mini2\", \"\", \"\"), \"version\", \"Mac mini\", \"\", \"\") or label_replace(label_replace(vector(1), \"device\", \"mac-studio1\", \"\", \"\"), \"version\", \"Mac Studio\", \"\", \"\") or label_replace(label_replace(vector(1), \"device\", \"mac-studio2\", \"\", \"\"), \"version\", \"Mac Studio\", \"\", \"\") or label_replace(label_replace(vector(1), \"device\", \"mac-studio3\", \"\", \"\"), \"version\", \"Mac Studio\", \"\", \"\") or label_replace(label_replace(vector(1), \"device\", \"mac-studio4\", \"\", \"\"), \"version\", \"Mac Studio\", \"\", \"\") or label_replace(machine_hw_info{job=\"hkt-exporter-asmhk-macbook\"}, \"device\", \"mac-book1\", \"\", \"\") ",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Status (Canvas)",
   "type": "canvas",
   "gridPos": { "h": 13, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(up{device=\"mac-mini1\"}, \"device\", \"mac-mini1\", \"\", \"\") or label_replace(vector(1), \"device\", \"mac-mini2\", \"\", \"\") or label_replace(vector(0), \"device\", \"mac-studio1\", \"\", \"\") or label_replace(vector(1), \"device\", \"mac-studio2\", \"\", \"\") or label_replace(vector(1), \"device\", \"mac-studio3\", \"\", \"\") or label_replace(vector(0), \"device\", \"mac-studio4\", \"\", \"\") or label_replace(up{device=\"mac-book1\"}, \"device\", \"mac-book1\", \"\", \"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "System Alerts", "type": "alertlist", "gridPos": { "h": 9, "w": 10, "x": 0, "y": 13 } },
  {
   "title": "Workflow Errors",
   "type": "table",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 13 },
   "targets": [
    {
     "limit": 100,
     "metricsQueryType": "range",
     "query": "{ name = \"workflow.execute\" && status = error } | select(span.n8n.workflow.id, span.n8n.workflow.name)",
     "spss": 20,
     "tableType": "spans"
    }
   ]
  }
 ]
}